import type { MediaWithExif } from "~/shared/types";

export const mockMediaList: MediaWithExif[] = [
  {
    name: "sunset_view.jpg",
    size: 2048576, // ~2MB
    type: "image/jpeg",
    lastModified: 1712630000000,
    exif: {
      title: "Beautiful Sunset",
      description: "A sunset over the ocean with vibrant orange colors.",
      subject: "Nature",
      keywords: ["nature", "sunset", "ocean", "vibrant"],
      rating: 5,
      author: "Jane Smith",
      license: "CC BY 4.0",
    },
  },
  {
    name: "company_logo.png",
    size: 153600, // 150KB
    type: "image/png",
    lastModified: 1712543600000,
    exif: {
      title: "Company Logo",
      description: "Official logo for Acme Corp.",
      keywords: ["logo", "branding", "corporate"],
      rating: 3,
      author: "Acme Design Team",
      license: "All Rights Reserved",
    },
  },
  {
    name: "mountains_trip.jpeg",
    size: 5242880, // 5MB
    type: "image/jpeg",
    lastModified: 1712400000000,
    exif: {
      title: "Mountain Trip 2023",
      description: "Hiking through the rocky mountains during summer.",
      subject: "Nature",
      keywords: ["mountains", "hiking", "summer", "rocky"],
      rating: 4,
      author: "John Doe",
      license: "Creative Commons",
    },
  },
  {
    name: "abstract_background.png",
    size: 3145728, // 3MB
    type: "image/png",
    lastModified: 1712300000000,
    exif: {
      title: "Abstract Background 1",
      description: "Blue and purple abstract shapes.",
      subject: "Abstract",
      keywords: ["abstract", "background", "blue", "purple"],
      rating: 2,
      author: "Alice Wonderland",
      license: "Public Domain",
    },
  },
  {
    name: "user_avatar.jpg",
    size: 51200, // 50KB
    type: "image/jpeg",
    lastModified: 1712200000000,
    exif: {
      title: "Default Avatar",
      description: "Fallback user avatar image.",
      keywords: ["avatar", "user", "profile"],
      rating: 0,
      author: "System",
      license: "MIT",
    },
  },
  {
    name: "forest_trail.jpg",
    size: 4194304,
    type: "image/jpeg",
    lastModified: 1712100000000,
    exif: {
      title: "Deep Forest Trail",
      description: "A narrow path through a dense green forest.",
      subject: "Nature",
      keywords: ["forest", "trail", "nature", "green"],
      rating: 4,
      author: "Robert Frost",
      license: "CC BY 3.0",
    },
  },
  {
    name: "city_skyline.jpg",
    size: 2621440,
    type: "image/jpeg",
    lastModified: 1712000000000,
    exif: {
      title: "Metropolis at Night",
      description: "Golden lights illuminating the city skyscrapers.",
      subject: "Architecture",
      keywords: ["city", "skyline", "night", "urban"],
      rating: 5,
      author: "Berenice Abbott",
      license: "All Rights Reserved",
    },
  },
  {
    name: "vintage_camera.png",
    size: 1048576,
    type: "image/png",
    lastModified: 1711900000000,
    exif: {
      title: "Classic 35mm",
      description: "An old film camera on a wooden table.",
      subject: "Object",
      keywords: ["camera", "vintage", "photography", "retro"],
      rating: 3,
      author: "George Eastman",
      license: "Public Domain",
    },
  },
  {
    name: "ocean_waves.jpg",
    size: 3670016,
    type: "image/jpeg",
    lastModified: 1711800000000,
    exif: {
      title: "Crashing Waves",
      description: "Close up of sea foam on a rocky beach.",
      subject: "Nature",
      keywords: ["ocean", "waves", "beach", "water"],
      rating: 4,
      author: "Hokusai",
      license: "CC BY-SA 4.0",
    },
  },
  {
    name: "coffee_brew.jpg",
    size: 819200,
    type: "image/jpeg",
    lastModified: 1711700000000,
    exif: {
      title: "Morning Ritual",
      description: "Steam rising from a fresh cup of black coffee.",
      subject: "Still Life",
      keywords: ["coffee", "morning", "steam", "cafe"],
      rating: 4,
      author: "Juan Valdez",
      license: "MIT",
    },
  },
  {
    name: "neon_street.png",
    size: 4718592,
    type: "image/png",
    lastModified: 1711600000000,
    exif: {
      title: "Cyberpunk Alley",
      description: "Reflections of neon signs in a rain-slicked street.",
      subject: "Urban",
      keywords: ["neon", "cyberpunk", "reflections", "night"],
      rating: 5,
      author: "Syd Mead",
      license: "All Rights Reserved",
    },
  },
  {
    name: "desert_dunes.jpg",
    size: 5242880,
    type: "image/jpeg",
    lastModified: 1711500000000,
    exif: {
      title: "Sahara Sunset",
      description: "Long shadows over the rolling sand dunes.",
      subject: "Nature",
      keywords: ["desert", "dunes", "sand", "sunset"],
      rating: 4,
      author: "Gertrude Bell",
      license: "CC BY-NC 4.0",
    },
  },
  {
    name: "product_shot.jpg",
    size: 1572864,
    type: "image/jpeg",
    lastModified: 1711400000000,
    exif: {
      title: "Wireless Headphones",
      description: "Minimalist product photography on a white background.",
      subject: "Product",
      keywords: ["tech", "headphones", "minimal", "product"],
      rating: 3,
      author: "Dieter Rams",
      license: "Commercial Use",
    },
  },
  {
    name: "mountain_lake.jpg",
    size: 6291456,
    type: "image/jpeg",
    lastModified: 1711300000000,
    exif: {
      title: "Alpine Reflection",
      description: "Perfect mirror reflection in a high altitude lake.",
      subject: "Nature",
      keywords: ["lake", "mountains", "reflection", "alpine"],
      rating: 5,
      author: "Ansel Adams",
      license: "Public Domain",
    },
  },
  {
    name: "workspace_topdown.png",
    size: 2097152,
    type: "image/png",
    lastModified: 1711200000000,
    exif: {
      title: "Creative Desk",
      description: "Flat lay of a notebook, pen, and laptop.",
      subject: "Business",
      keywords: ["workspace", "productivity", "flatlay", "desk"],
      rating: 4,
      author: "Marie Kondo",
      license: "CC BY 2.0",
    },
  },
  {
    name: "portrait_study.jpg",
    size: 3145728,
    type: "image/jpeg",
    lastModified: 1711100000000,
    exif: {
      title: "Deep Thought",
      description: "A close up portrait with dramatic lighting.",
      subject: "Portrait",
      keywords: ["portrait", "face", "lighting", "expression"],
      rating: 4,
      author: "Annie Leibovitz",
      license: "All Rights Reserved",
    },
  },
  {
    name: "macro_leaf.jpg",
    size: 1048576,
    type: "image/jpeg",
    lastModified: 1711000000000,
    exif: {
      title: "Veins of Life",
      description: "Extreme macro shot of a green leaf's texture.",
      subject: "Nature",
      keywords: ["macro", "leaf", "texture", "nature"],
      rating: 3,
      author: "Karl Blossfeldt",
      license: "CC BY-SA 3.0",
    },
  },
  {
    name: "starry_night.jpg",
    size: 7340032,
    type: "image/jpeg",
    lastModified: 1710900000000,
    exif: {
      title: "Milky Way Galaxy",
      description: "Long exposure of the night sky in a dark park.",
      subject: "Space",
      keywords: ["stars", "astrophotography", "night", "space"],
      rating: 5,
      author: "Galileo",
      license: "Public Domain",
    },
  },
  {
    name: "architecture_detail.png",
    size: 1835008,
    type: "image/png",
    lastModified: 1710800000000,
    exif: {
      title: "Brutalist Geometry",
      description: "Sharp angles of a concrete museum building.",
      subject: "Architecture",
      keywords: ["architecture", "concrete", "geometry", "minimal"],
      rating: 4,
      author: "Le Corbusier",
      license: "All Rights Reserved",
    },
  },
  {
    name: "autumn_leaves.jpg",
    size: 2621440,
    type: "image/jpeg",
    lastModified: 1710700000000,
    exif: {
      title: "Golden Canopy",
      description: "Looking up through yellow maple trees.",
      subject: "Nature",
      keywords: ["autumn", "leaves", "gold", "trees"],
      rating: 4,
      author: "Henry David Thoreau",
      license: "CC BY 4.0",
    },
  },
  {
    name: "food_plating.jpg",
    size: 1310720,
    type: "image/jpeg",
    lastModified: 1710600000000,
    exif: {
      title: "Haute Cuisine",
      description: "Artistic presentation of a seafood dish.",
      subject: "Food",
      keywords: ["food", "gourmet", "plating", "restaurant"],
      rating: 5,
      author: "Gordon Ramsay",
      license: "Commercial Use",
    },
  },
  {
    name: "urban_exploration.jpg",
    size: 5242880,
    type: "image/jpeg",
    lastModified: 1710500000000,
    exif: {
      title: "Abandoned Factory",
      description: "Rust and decay in an old industrial hall.",
      subject: "History",
      keywords: ["urbex", "abandoned", "industrial", "decay"],
      rating: 3,
      author: "Lewis Hine",
      license: "CC BY-NC 2.0",
    },
  },
  {
    name: "cat_nap.png",
    size: 943718,
    type: "image/png",
    lastModified: 1710400000000,
    exif: {
      title: "Lazy Afternoon",
      description: "A ginger cat sleeping on a sunlit windowsill.",
      subject: "Animal",
      keywords: ["cat", "pet", "nap", "sunlight"],
      rating: 5,
      author: "Ernest Hemingway",
      license: "Public Domain",
    },
  },
  {
    name: "concert_crowd.jpg",
    size: 4718592,
    type: "image/jpeg",
    lastModified: 1710300000000,
    exif: {
      title: "Live Energies",
      description: "Silhouettes of people with hands in the air.",
      subject: "Music",
      keywords: ["concert", "music", "live", "crowd"],
      rating: 4,
      author: "Mick Rock",
      license: "All Rights Reserved",
    },
  },
  {
    name: "winter_chalet.jpg",
    size: 3407872,
    type: "image/jpeg",
    lastModified: 1710200000000,
    exif: {
      title: "Snowy Retreat",
      description: "A cabin covered in deep snow at twilight.",
      subject: "Leisure",
      keywords: ["winter", "snow", "cabin", "twilight"],
      rating: 5,
      author: "Jack London",
      license: "CC BY 3.0",
    },
  },
];
